info:
    contact:
        email: xixicat@gmail.com
        phone: 0755-82890987

spring:
  profiles:
    active: test

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

