server:
  port: 8088

spring:
  output:
    ansi:
      enabled: never

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    platform: mysql
    url: jdbc:mysql://192.168.1.124:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    ##集群对外暴露的IP
    host: 192.168.1.124
    port: 6379

  batch:
    job:
      enabled: false
    initializer:
      enabled: false

file:
  importExcelService: http://192.168.1.124:8088/excel/
  filePath:  /Users/leadu/Documents/data/device/
  deviceImgPath:  /Users/leadu/Documents/data/device/
  impExcelPath:  /Users/leadu/Documents/data/excel/
  androidFilePath:  /Users/leadu/Documents/data/android/
  corpInnerFilePath: /Library/WebServer/Documents/corpInnerFile/
  requestFrontPath: http://192.168.1.124:8088/
  newsFilePath:  /Users/leadu/Documents/data/information/news/
  requestNewsFilePath: http://192.168.1.124:8088/information/news/
  companyFilePath:  /Users/leadu/Documents/data/information/companyFile/
  requestCompanyFilePath: http://192.168.1.124:8088/information/companyFile/
  requestAndroidFilePath: http://192.168.1.124:8088/android/


systemParam:
  distance: 1
  minute: 5
  reportResortDistance: 1





#sms:
#  ipAddr: 222.73.56.19
#  port: 6974


request:
  tubaServerUrl: http://192.168.1.124:9983
  baiduServerUrl: http://api.map.baidu.com
  wxServerUrl: https://api.weixin.qq.com
  qqServerUrl: http://apis.map.qq.com
  cmppServerUrl: http://10.10.1.31
